version: '3.6'
services:
      
  frontend:
    build:
      context: ./frontend
      dockerfile: .docker/prod/Dockerfile
      args:
        - "REACT_APP_API_URL=${REACT_APP_API_URL}"
    environment:
      - "REACT_APP_API_URL=${REACT_APP_API_URL}"
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}