version: '3.6'

services:
  
  traefik:
    image: traefik:v2.0
    command: 
      - "--api.insecure=true" 
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker"
      - "--providers.docker.defaultrule=Host(`${DOMAIN}`)"
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - traefik.enable=true
      - "traefik.http.routers.api.rule=PathPrefix(`/api`) || PathPrefix(`/dashboard`)"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.services.api.loadbalancer.server.port=8080"

  frontend:
    labels:
      - traefik.enable=true
      - "traefik.http.routers.frontend.rule=PathPrefix(`/`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"
